### ISSUE TITLE
Leaderboard and Matches says 'Forbidden' when try to access

### ISSUE THREAD

**Issue by MightySheep** [beyond-all-reason/teiserver#102]
I'm signed in and I can't access:
https://server4.beyondallreason.info/teiserver/battle/ratings/leaderboard
https://server4.beyondallreason.info/teiserver/battle/matches

Example:
https://streamable.com/gncy81

**Comment by MightySheep** [comment]
I just realized signing in with my normal email address signed me into an account called 'noober'. I don't know if that even exists or it's banned or something. I don't have these issues now that I signed into my normal account.

**Comment by Teifion** [comment]
That's the intended behaviour for a banned account, it should have happened in the other pages though. Still a bug but not the bug initially thought.

**Comment by sra1kumar-NULL** [comment]
Can I work on this fix @Teifion  @MightySheep  could you developers provide me any dummy credentials for login and test

**Comment by Teifion** [comment]
You are very welcome to work on it. I suggest setting up a local environment and using `mix teiserver.fakedata` to get data to play with. That way you can make changes and test them.

**Comment by sra1kumar-NULL** [comment]
> 

I've tried to fix the issue but can't able to fix it , don't even understand where it's going wrong.Anyways thanks for your time @Teifion

**Comment by fumbleforce** [comment]
Looked at this briefly, for future note. The error is likely a missing "teiserver" permission for the user.
I believe that if you sign up directly on the website without going through the game lobby signup, you get an account without this permission, which will crash certain pages rather than giving an elegant permission denied page.
