### ISSUE TITLE
Changing email address to a duplicate causes issues

### ISSUE THREAD

**Issue by Teifion** [beyond-all-reason/teiserver#118]
If you go to edit your own email address on the site and the address is already taken it shows an error but doesn't correctly communicate the cause of the error.

**Comment by kozak-codes** [comment]
![image](https://github.com/beyond-all-reason/teiserver/assets/1368558/b5fc3cd0-22da-40cd-b038-b957370243a0)

Seems to be working correctly unless I'm mistaken
