### ISSUE TITLE
Add config option to refuse to rate games if balance deviation is too high

### ISSUE THREAD

**Issue by Teifion** [beyond-all-reason/teiserver#148]
There should be a runtime config added which allows refusing to rate games if one or more of their ratings fall outside of a give parameter. The original request specifies rating deviation but it might be useful to have more options.

Discord message - https://discord.com/channels/549281623154229250/564591092360675328/1134142761826795622

Depends on #147

**Comment by L-e-x-o-n** [comment]
OpenSkill should already have smaller rating changes if balance deviation is too high, closing this as unnecessary for now.
