### ISSUE TITLE
Tweak infolog view for useablility

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#15]
I LOVE the infolog view, and may I have 4 requests for it?
1. Display username in the title of it. 
2. Have metadata before the contents in the display field
3. maybe optionally have a larger-by default contents field?
4. Maybe a button to resolve or delete (gdpr?) a log? 

![image](https://user-images.githubusercontent.com/109391/147480048-f4b8323d-aa6f-4cc8-a614-1f8a2b12fea7.png)

**Comment by Teifion** [comment]
> 1    Display username in the title of it.
Will be easy, no problem

> 2    Have metadata before the contents in the display field
Sure thing, also easy

> 3    maybe optionally have a larger-by default contents field?
Can do though the idea for that is you'd be copy-pasting them to an actual log viewer rather than the text field here

> 4    Maybe a button to resolve or delete (gdpr?) a log?
I was going to start auto-deleting logs after a certain period of time anyway. Is 7 days long enough to keep them?

**Comment by Teifion** [comment]
Items now addressed, closing the issue.
