### ISSUE TITLE
auto-join users on registration to a country-channel

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/teiserver#173]
title says all

**Comment by Teifion** [comment]
Chat rooms might be going away and the geoip is pretty innacurate so while I'm not marking this as "won't do" yet I would expect it to end up in that category.

**Comment by FIr3baL** [comment]
That's ok.
Then just move it over to byar-chobby please.

It could be done, when chobby language support gets activated. But same status - i don't know, if i ever do it.
Technically it's already implemented, but it needs dev-organization a lot...
https://github.com/beyond-all-reason/BYAR-Chobby/issues/404

Chobby could auto-join you into a country-channel on picking a language. Though most users prefer to stay with original english. Or any better idea comes up in the future.

**Comment by L-e-x-o-n** [comment]
Closing for the reasons Teifion mentioned.
