### ISSUE TITLE
redirect me after login to original url

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/teiserver#175]
If users click "Reset password" or "Edit password" in chobby. they are redirected to browser urls:
https://server4.beyondallreason.info/forgot_password
and
https://server4.beyondallreason.info/teiserver/account/security/edit_password

By default nobody is logged in on teiserver, so login window shows up and after login the main menu is shown, not our already told direct link. https://server4.beyondallreason.info/

So in general, remember the original target during login window and redirect me to it once logged in.

**Comment by Teifion** [comment]
I thought it was already doing this but it appears something changed and it stopped, this is a good issue to raise thank you :)

**Comment by geekingfrog** [comment]
I did fix the issue, but only for non liveview code in https://github.com/beyond-all-reason/teiserver/pull/309 I believe. Didn't touch any liveview stuff
