### ISSUE TITLE
More granular system for controlling whether a game is rated or not

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#199]
The following functionality has been requested:

- Allow players to make a match unrated if they wish
- Certain match settings and modoptions should not allow a match to be rated, and must be easily configurable by devs
- Display whether a match will be rated in the lobby, before the game starts

We now have the `is_ranked` SPADS battle setting, that players can change to `0` to make the game unranked. It's `1` by default, thus, all games are ranked by default.

Ideally, a list of modoptions should be configurable on the server. Any game with at least 1 of these modoptions enabled should have its `is_ranked` modoption changed to `0`. If players try to manually change this value back while any of these modoptions are enabled, (i.e. `!bset ranked_game 1`), then the server should either block this command, or otherwise force `ranked_game` back to `0` immediately after, and a message should be shown to players, e.g. `The following modoptions must be disabled for the game to be ratable: disable_fogofwar, norush`.

Does this sound feasible/sensible for implementing into Teiserver?

**Comment by StanczakDominik** [comment]
Yeah, I suspect that this is perfectly sensible. Trace how `!bset ranked_game 1` was added, then hard-code such a disable for some utterly insane unused modoption (@TheSilverHornet modoption master, have you a recommendation?) as a module-level variable. Then I can add, or lead you through adding, a web interface that configures them.

Believe it or not, I think this is a...

**Comment by L-e-x-o-n** [comment]
Linked issue #181

**Comment by L-e-x-o-n** [comment]
Closing in favour of #181
