### ISSUE TITLE
Add flags to leaderboard API responses

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#201]
Would it be possible to add player's flag icon strings to the leaderboard responses?

https://server4.beyondallreason.info/teiserver/api/public/leaderboard/Team

**Comment by Teifion** [comment]
Yes, this should be both very possible and very easy.

**Comment by Teifion** [comment]
@L-e-x-o-n might be interested

**Comment by L-e-x-o-n** [comment]
What should be the response when the player's flag is not known for whichever reason? Should the country key not be present at all or should it have some default value?

**Comment by Teifion** [comment]
The response to no known flag is typically `??`
