### ISSUE TITLE
Expand leaderboards

### ISSUE THREAD

**Issue by RebelNode** [beyond-all-reason/teiserver#203]
The top 30 leaderboards are remnants of a time when we literally didn't have 100 active players to fill a top 100 leaderboard. I think they could be expanded to top 100 now that our playerbase has grown 20-fold.

I started this discussion in https://discord.com/channels/549281623154229250/1179660574280388728 but apparently it needs teiserver api update first: https://server4.beyondallreason.info/teiserver/api/public/leaderboard/Team

Obviously an opinionated "issue", but the "top30" always felt pretty arbitrary to me at least unless there's some technical reason to not return a bigger list.

**Comment by Teifion** [comment]
It's mostly arbitary, there are considerations of page size (returning a 1000 row table for example, not great) but they can be overcome.

**Comment by RebelNode** [comment]
I looked at it for a bit. Is this just a value in https://github.com/beyond-all-reason/teiserver/blob/master/lib/teiserver_web/controllers/api/public_controller.ex#L28 ? Didn't set up a proper testing environment and stuff, just and "educated guess" if you will.

**Comment by RebelNode** [comment]
Solved by https://github.com/beyond-all-reason/teiserver/commit/c5c6ce3f28c0143686ad6fe3a8e87b10d10eaa1b
