### ISSUE TITLE
When restarting all spadses, all of the SML clients gather into the first open lobby and duke it out.

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#213]
And yeah, this results in everyone getting disconnected.

**Comment by Teifion** [comment]
I brought Battle Royale gameplay to BAR. You're welcome? :P

**Comment by Beherith** [comment]
Note to self: dont restart all spadses at once :P

**Comment by Teifion** [comment]
In all seriousness it should be quite easy to have a command to send each SML manager a command telling it to disconnect all clients and keep them disconnected for X minutes.

**Comment by L-e-x-o-n** [comment]
Closing because Server Manged Lobbies are currently unused. Can be reopened in the future if SMLs are revvied.
