### ISSUE TITLE
Failures of some telemetry in match_monitor_server

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#226]
2024-03-12 20:35:37.509 [error] request_id=MatchMonitorServer  GenServer #PID<0.5341.0> terminating
** (KeyError) key :lobby_id not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (teiserver 0.1.0) lib/teiserver/battle/servers/match_monitor_server.ex:259: Teiserver.Battle.MatchMonitorServer.handle_info/2
    (teiserver 0.1.0) lib/teiserver/battle/servers/match_monitor_server.ex:116: anonymous fn/3 in Teiserver.Battle.MatchMonitorServer.handle_info/2
    (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (teiserver 0.1.0) lib/teiserver/battle/servers/match_monitor_server.ex:115: Teiserver.Battle.MatchMonitorServer.handle_info/2
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:direct_message, 26620, ["match-chat-name <DannyBoj>:<0> dallies: I sent 656 metal to JaroZrucharo"]}

**Comment by L-e-x-o-n** [comment]
Closing for now because this no longer seems to appear in logs.
