### ISSUE TITLE
Make the server configurable at runtime, not compile time.

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/teiserver#236]
Currently the server configuration is part of the **build process**, including the `prod.secret.exs`, this is very cursed for many reason:
 - Any change to configuration requires recompile of application
 - Because config can impact which dependencies are compiled, when building in reproducible way, changing config invalidates a lot of caching
 - We can't prebuild anything, or build the software outside of the production machine which should be the only place where secrets are stored unencrypted
 - We can't use the same exact binary version in the integration and production environment
 - This highly increases the production server deployment complexity as now it also needs to contain the CI to build the software

This needs to be refactored to load configuration at **runtime**, when server starts, potentially also allowing to reload part of the configuration without having to restart the whole server just like it's done in many other servers that are supposed to be long running.

**Comment by p2004a** [comment]
Most likely need to steal by how it's done in https://github.com/Teifion/angen/blob/master/config/runtime.exs

**Comment by geekingfrog** [comment]
Other useful link:
* elixir guide about [configuration and release](https://hexdocs.pm/elixir/config-and-releases.html)
* the [doc](https://hexdocs.pm/elixir/main/Config.html) for the config module

**Comment by geekingfrog** [comment]
FYI: I started working on that

**Comment by StanczakDominik** [comment]
Closed by #278
