### ISSUE TITLE
Stop depending on non-free fontawesome

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/teiserver#242]
Teiserver depends on the non-free version of https://fontawesome.com/. This makes it harder to build and distribute. Everyone that wants to, has to acquire the license themselves. This is very problematic in the open source project like this one.

**Comment by Teifion** [comment]
I have released an updated version of the library I started using which should help - https://hexdocs.pm/fontawesome_icons/Fontawesome.html

All you would need to do is convert all raw fontawesome calls to use the component already in use by the server and then you can control it with a config. It was one of the earlier things I did with Angen but didn't update the docs.
