### ISSUE TITLE
TeamPreset property for battles

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#26]
Ideally, I think battles should implement a mandatory property that dictates the team configuration. This is already semi-supported in SPADS by the way of presets, but I think it should be promoted to the master server level because it's an important and required property in the configuration of battles.

Duel = 2 teams, exactly 1 player on each team
Teams = 2 teams, at least 4 players (2v2), even number of players on each team
FFA = more than 2 teams, exactly 1 player on each team
TeamFFA = more than 2 teams, at least 6 players (2v2v2), even number of players on each team
Custom = anything goes. primarily used for odd teams, e.g. 2v1 or 2v1v1

Instead of determining the TeamPreset by examining the existing team setup, the battle host should dictate the necessary team requirements based on its current TeamPreset value. This would mean that if 2 players joined a battle set to the Teams preset and tried to start a 1v1, then the battle host should not be allowed to start the game.

By supporting and enforcing this at a server level, we can ensure battles are what they say they are, and make it easier for players to find the types of battles they're interested in. It will also aid in preventing uneven games from starting, as players would explicitly need to change the preset to Custom to allow this. Similarly, it may prevent uneven games from being rated, or games being rated against the incorrect ladder. It would also be easy to tie the StartPosType mode to the TeamPreset value, e.g. the battle changing to fixed positions for FFA.

This would need implementing in Teiserver and SPADS, but it may be easier to leave SPADS alone and implement it in a new tachyon-based autohost in the future. For the transition period, I suggest all battles be assumed to have a default TeamPreset of Custom unless they specify otherwise. Then eventually it can be made a mandatory property if we ever shift to Tachyon-only.

**Comment by MasterBel2** [comment]
WRT SPADS we already have some sort of management of this – different presets, and likewise it should be simple enough to report whether autobalance is on or off? Games with autobalance on require `!forcestart` to start - people have to be conscious of it (admittedly, the current vote interface in Chobby isn't so obvious about what you're voting on). I also suspect [it would be simple to write a plugin that simply reports this to Teiserver](http://planetspads.free.fr/spads/doc/spadsPluginApiDoc.html#onPresetApplied-self-oldPresetName-newPresetName).
The case I'm less sure about is the case of just 2 players in a battle, which could become anything - team/duel/custom etc.

iirc blocking 1v1 in team preset about comes down to changing a [single number in a config file](https://github.com/beyond-all-reason/spads_config_bar/blob/main/etc/spads.conf#L170). 

There's also a proliferation of cases that could occur here that Teiserver might not want to vet, but that would be useful for users to be made aware of – teamsize? AIs / Raptors / Scavs? And permutations thereof.
