### ISSUE TITLE
Party page's "KICK" and "CANCEL INVITE" buttons no longer function.

### ISSUE THREAD

**Issue by DeviousNull** [beyond-all-reason/teiserver#267]
I see this issue myself, and a few others that I talked to have confirmed that they see the same issue.

1. Reproduction Instructions:
2. Create a party on https://server4.beyondallreason.info/teiserver/account/parties
3. Invite someone
4. Click "CANCEL INVITE" for them
- Result: Nothing happens. No Console output or HTTP requests appear in the browser's DevTools.
5. Wait for the invited player to accept the invite
6. Click "KICK" for them
- Result: Nothing happens. No Console output or HTTP requests appear in the browser's DevTools.

Tested using Google Chrome, Version 123.0.6312.123 (Official Build) (64-bit)

Crossposted from https://discord.com/channels/549281623154229250/1229185821920333855

**Comment by L-e-x-o-n** [comment]
Tested locally, no errors in logs.
```
[debug] HANDLE EVENT "cancel_invite" in TeiserverWeb.Account.PartyLive.Show
Parameters: %{"userid" => "42"}
```
