### ISSUE TITLE
Reschedule daily Oban jobs to 8AM instead of 2AM which is still in US peak

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#288]

**Comment by Beherith** [comment]
jobname	meanms	count	otalms
Teiserver.Logging.Tasks.PersistServerMinuteTask	17	9501	170529
Teiserver.Moderation.RefreshUserRestrictionsTask	100	9501	952450
Teiserver.Battle.Tasks.PostMatchProcessTask	1300	9501	12353368
Teiserver.Admin.HourlyCleanupTask	1113	159	177118
Teiserver.Battle.Tasks.CleanupTask	494501	158	78131240
Teiserver.Admin.DailyCleanupTask	120071	7	840501
Teiserver.Account.Tasks.DailyCleanupTask	122	7	857
Teiserver.Telemetry.EventCleanupTask	424	7	2973
Teiserver.Logging.AggregateViewLogsTask	1011	7	7078
Teiserver.Logging.Tasks.PersistServerDayTask	4384	7	30689
Teiserver.Logging.Tasks.PersistServerWeekTask	28	8	227
Teiserver.Logging.Tasks.PersistServerMonthTask	0	7	5
Teiserver.Logging.Tasks.PersistServerQuarterTask	0	7	5
Teiserver.Logging.Tasks.PersistServerYearTask	0	7	5
Teiserver.Logging.Tasks.PersistMatchDayTask	7513	7	52596
Teiserver.Logging.Tasks.PersistMatchMonthTask	0	7	5
Teiserver.Telemetry.InfologCleanupTask	453	7	3171
Teiserver.Logging.Tasks.PersistUserActivityDayTask	1297	7	9079
Teiserver.Game.AchievementCleanupTask	5	7	38
Teiserver.Account.RecalculateUserDailyStatTask	16431	13	213603

**Comment by geekingfrog** [comment]
Is this causing problem on the server? Some jobs take a bit of time, but is the DB actually under heavy load?
Also, how do you get this useful infodump?
Changing the scheduling of these job [is trivial](https://github.com/beyond-all-reason/teiserver/blob/master/config/config.exs#L116-L157) but I'd like to better understand the problem to solve here.

**Comment by Beherith** [comment]
They arent causing direct problems. But 2am is still busy USA time so its sensible to do when quietest
