### ISSUE TITLE
Mix dialyzer fails

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/teiserver#298]
## Test Steps
Run
```
mix dialyzer
```
This does typechecking. You will get this error:
```
lib/teiserver/helpers/oban_logger.ex:43:call
The function call will not succeed.

System.convert_time_unit(any(), :native, :milliseconds)

breaks the contract
(integer(), time_unit() | :native, time_unit() | :native) :: integer()
```

Looking at the valid units
https://hexdocs.pm/elixir/1.12/System.html#t:time_unit/0

I think it should be `:millisecond` not `:milliseconds`

@Beherith this is a file you have worked on recently so it would be good if you can investigate.

**Comment by StanczakDominik** [comment]
Addressed in #304
