### ISSUE TITLE
On trying to change email to one already taken by another user, notify the user that it's already taken 

### ISSUE THREAD

**Issue by StanczakDominik** [beyond-all-reason/teiserver#305]
Apparently it just fails silently right now

**Comment by geekingfrog** [comment]
What's the flow? going under your own account > details > edit the email address?

**Comment by StanczakDominik** [comment]
I just wrote that down quickly while handling a ticket 😅 repro details should have been here in the first place, though. 

1. Open chobby
2. Log in
3. Account -> Recover/Change tab
4. type a taken "New email address": value
5. see "Request accepted, enter verification code received via email" green message - it should probably check whether the email is valid instead
