### ISSUE TITLE
Missing user data in s.auth.login response

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#31]
`country` and `icons` properties are returned for users in the `s.user.user_and_client_list` response, but that data seems to be missing from `s.auth.login`. I suspect it'll be missing from `s.auth.verify` too

**Comment by Teifion** [comment]
@L-e-x-o-n probably a really good first-Tachyon item for you to look at if you are happy to.

**Comment by L-e-x-o-n** [comment]
Yes, will do it
