### ISSUE TITLE
JSONSchema generation

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#32]
Just for clarity, I've been mapping the server schema explicitly in my typescript client here:
https://github.com/Jazcash/tachyon-client/blob/master/src/model/requests.ts
https://github.com/Jazcash/tachyon-client/blob/master/src/model/responses.ts

This provides typings for my TypeScript client API, and I also use them to generate JSONSchema validators that I parse against the actual server responses to help like this:

![image](https://user-images.githubusercontent.com/1434248/169362886-2e8f6eeb-348b-4a5c-822b-1868ee0848f6.png)

[JSONSchema](https://json-schema.org/) files are just JSON objects which also describe how other JSON objects should look.

Ideally, these would be generated by the server for all requests and responses to ensure there's always a one-to-one mapping between the server and clients, with only one source of truth. They can be used to automatically generate API docs for clients, or similarly generate TypeScript definitions.

I think there's other projects that achieve similar goals, like Google's [Protocol Buffers](https://developers.google.com/protocol-buffers), which might be worth looking into.

**Comment by Teifion** [comment]
Closed as now part of the Tachyon repo.
