### ISSUE TITLE
Lobby response includes the password

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#33]
![image](https://user-images.githubusercontent.com/1434248/169610661-0bc1627b-d89d-4b68-8e97-b576255125fc.png)

e.g. when requesting a list of lobbies via `c.lobby.query`, the `s.lobby.query` response includes the password for all private lobbies. Should probably be replaced with `passworded: boolean` to denote whether the lobby requires a password to join it or not.

**Comment by Teifion** [comment]
Fixed
