### ISSUE TITLE
`s.lobby.updated` only send updated properties

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#34]
Would it be possible to send partial differences of just the properties that changed instead of the full lobby object?

e.g.

```json
{
    "cmd": "s.lobby.updated",
    "lobby": {
        "map_name": "Comet Catcher Remake 1.8"
    }
}
```

**Comment by Teifion** [comment]
It's possible but a bit trickier to do based on the way it's been made for Spring. How big an improvement would it be for you if it only sent the required properties?

**Comment by Jazcash** [comment]
I can manage fairly comfortably without this change by just diffing the incoming object to the last one, so not a big worry for me. Although it does feel slightly unwieldy to receive the full object back for any change, especially with the huge tags object.

I'm not sure if we care about message bandwidth at this stage, but I think this would be at the top of the list if it was ever something that needed optimising.

Happy for this to be low priority for now if it's awkward.

**Comment by Teifion** [comment]
The tags is a really good point. I think it's worth addressing.

**Comment by Teifion** [comment]
Modoptions (previously tags) and Bots are now sent out as specific updates and polled separately. Does this resolve the issue to your satisfaction?

**Comment by Jazcash** [comment]
That's kind of unrelated to this issue, which is specifically about only sending data for updated properties and omitting properties that didn't change
