### ISSUE TITLE
Lingering friends/mutes

### ISSUE THREAD

**Issue by Teifion** [beyond-all-reason/teiserver#35]
When a user is deleted they are not removed from the friend/mute lists of other users. They should be.

**Comment by Penguin2600** [comment]
@Teifion Thinking about picking this one up as my 3rd, any additional acceptance criteria or details you think I should know before beginning?

**Comment by Teifion** [comment]
None at all, just make sure you get an understanding of how users work here (it's not as obvious as it should be, currently making changes to fix that but they'll happen after this PR).
