### ISSUE TITLE
Investigate why Chobby receives duplicate ADDUSER commands

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/teiserver#350]
Fireball has reported that Chobby is receiving duplicate ADDUSER commands. I tried to look into it briefly but not really sure.
https://discord.com/channels/549281623154229250/1195389146873729204/1258490543676199022

@geekingfrog Any ideas?

**Comment by L-e-x-o-n** [comment]
Closing for now as it doesn't seem to be a high priority issue, with enough information to reproduce reliably. Feel free to reopen if needed.
