### ISSUE TITLE
[Feature]: spring-protocol: message batching

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/teiserver#360]
### Describe the Feature

Spring protocol allows batching of commands by "\n".
Gather servermessges for each client for a certain amount of time and send them concatenated to the client.
E.G. 0,5 sec.

### Expected Behavior

Overall reduction of network traffic. Less tcp-overhead compared to tcp-content. Less packages in total.
On client-side one would see a little delay for server reactions to sent commands by clients.

### Additional context

A random log showed me between 3-15 servermessages per second, which came in as 1 package per message.
The only exception to this behaviour, known by me, are all these thousand infos after a login success, which are already batched.

This idea came to my mind during analysis of client -> server communication.
My knowledge is too limited to recommend this change,

**Comment by L-e-x-o-n** [comment]
While this is a good idea, I think it's not worth doing for Spring protocol which will be replaced with Tachyon.

**Comment by FIr3baL** [comment]
That's fine.
