### ISSUE TITLE
[Bug]: !rename not working after the first

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/teiserver#371]
### Describe the Bug
Recently there has been an updated to SPADS plugins allowing non bossed people to rename a lobby. Try these commands when alone in lobby.
```
!rename test
!rename test2
```

Second rename will fail

### Reproduce the bug

Ensure you have the latest files from: https://github.com/beyond-all-reason/spads_config_bar/pull/134/files
in your local copy of SPADS.

Launch Chobby
```
!rename test
!rename test2
```

Second one will fail. Try bossing yourself
```
!boss jauggy
$rename test
$rename test2
```
I believe it will now pass

### Additional context

I believe that there is a check inside consul_commands.ex
When you use `$rename` as boss it will enter here
```
      senderid != lobby.founder_id ->
        # We have to do this so we don't block the get_state call from the LobbyServer
        # when it tries to query the rating values
        spawn(fn ->
          :timer.sleep(500)
          Battle.rename_lobby(state.lobby_id, new_name, senderid)
        end)
 ```
 
 However, when SPADS tells teiserver to rename that part is not true and instead it goes here:
```
      lobby.player_rename ->
        state

      true ->
        Battle.rename_lobby(state.lobby_id, new_name, nil)

        state
```
The first time it will go to the "true" part and work. The next time it will go to the lobby.player_rename part and do nothing.

Need to understand why Teifion put a timer sleep when renaming the lobby when you do it via `$rename`

**Comment by jauggy** [comment]
It seems like Teifion added code to prevent spads from updating the name of a lobby after it has be renamed by a player. No idea why it's there. Maybe spads renames lobbies when it's reset?

**Comment by jauggy** [comment]
Can you explain what function you are talking about?

**Comment by jauggy** [comment]
The `def sendTachyonBattleTitle():` doesn't even work properly. Tried in prod hosting a room and changing presets and the name didn't update appropriately. I honestly think the request to change name in that function could even be removed.

**Comment by jauggy** [comment]
@L-e-x-o-n this is not fixed can you reopen? @DeviousNull  still needs to make changes. Read here: https://github.com/beyond-all-reason/teiserver/pull/374

> This PR specifically does not update the $rename command, as that would impact player-set lobby names for any SPADS instances that still use the old BarManager code. Once the new plugin code is running on all servers, I can submit a very short PR to update $rename and fix h

ttps://github.com/beyond-all-reason/teiserver/issues/371.

**Comment by L-e-x-o-n** [comment]
Ah it got auto closed, sorry.
