### ISSUE TITLE
[Bug]: ADDUSER missing some parameters

### ISSUE THREAD

**Issue by FIr3baL** [beyond-all-reason/teiserver#387]
### Describe the Bug

A user showed a log, where ADDUSER was sent with missing arguments.
https://discord.com/channels/549281623154229250/1267540201861812445
`ADDUSER DiscordBridge  5388`
Usually it looks like this
`ADDUSER DiscordBridge GB 5388 Teiserver Internal Client`

It's not known, if this is a single occurence or if this happens regularly.

### Reproduce the bug

idk

**Comment by jauggy** [comment]
@FIr3baL are you able to handle the country if it is ??

**Comment by jauggy** [comment]
Looking inside client.ex the country is set on login and cannot be nil
```
  def login(user, protocol, ip \\ nil, token_id \\ nil) do

        country: stats["country"] || "??",
```
But I'm guessing bots don't login.

Inside spring_out.ex, we could check for nil country and use "??" instead
```
  defp do_reply(:add_user, client) do
    "ADDUSER #{client.name} #{client.country} #{client.userid} #{client.lobby_client}\n"
  end
```

**Comment by L-e-x-o-n** [comment]
Teiserver internal bots do login (`internal_client_login` in `cache_user.ex` ). They have their country set to default server flag, in this case `GB` so it should not be `nil`.  `get_country` in `cache_user.ex` gets country.
I think we should try finding the cause first before checking in `do_reply`

**Comment by FIr3baL** [comment]
> @FIr3baL are you able to handle the country if it is `??` because if yes I could make that the default country. Currently the default country is `nil`

Yes, the country may be anything. Chobby checks if an image exists with that name. If not, the default image is displayed.
But the argument must consist of 4 seperated strings. It's matched against this pattern, otherwise chobby logs an error.
```lua
(%S+)%s+(%S+)%s+(%S+)%s*(.*)
```

**Comment by L-e-x-o-n** [comment]
@jauggy are you working on this?

**Comment by jauggy** [comment]
@L-e-x-o-n I am not working on this. I think low priority is appropriate because it's hard to reproduce.

**Comment by FIr3baL** [comment]
Closed for tidiness.
