### ISSUE TITLE
[Feature]: Remove teaser if lobby title is too long

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/teiserver#391]
### Describe the Feature

Have teiserver detect that a lobby title is too long, and if so remove the teaser. The teaser is the bit of information that exists between the title and the rating restrictions. Teasers are given by SPADS.

### Expected Behavior

Check the length of the title with the teaser and rating restrictions, and if too long (not sure the char count but something like 50) then do not display the teaser. See the image attached. The `| Teams 8 vs 8 | ` should be removed if too long.

### Screenshots

![1](https://github.com/user-attachments/assets/39689668-d99c-4195-bcf3-ee280a07687f)

**Comment by L-e-x-o-n** [comment]
Not sure about this. I think this should be implemented client side as it depends on user resolution if something will fit on their screen or not.

Space could also be optimised by shorter teasers, for example "Teams 8 vs 8" could be just" 8 vs 8".

**Comment by jauggy** [comment]
@FIr3baL is this possible to do in chobby?

**Comment by jauggy** [comment]
We could use regex to shorten the teaser in teiserver using regex match `\w vs \w`

This would make `Boss name | Custom Battle 8 vs 8` become simple `8 vs 8`

**Comment by L-e-x-o-n** [comment]
> We could use regex to shorten the teaser in teiserver using regex match `\w vs \w`
> 
> This would make `Boss name | Custom Battle 8 vs 8` become simply `8 vs 8`

I still think this is something that should be done either SPADS side (send shorter) or Chobby side (regex match and shorten if too long to fit)

**Comment by jauggy** [comment]
Have created tickets on SPADS and Chobby repos.
