### ISSUE TITLE
[Feature]: Make webchat read only for most people

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/teiserver#399]
### Describe the Feature

Make webchat read only for most people. Currently anyone can use webchat from website including spammers or people who have been banned from the lobby.

### Expected Behavior

Login to website. Go to lobbies. Select Chat. The Send button and text input should only be visible for mods/admins. It should not be visible for academy managers and mentors. This will allow normal users to read chat but not send messages.

Allowing contributors access is optional. I don't really see a use case for them using it.

### Screenshots

![1](https://github.com/user-attachments/assets/b3e12293-72d8-4e36-8489-2541184b9df7)

### Additional context

Discord discussion: https://discord.com/channels/549281623154229250/1269606132024868986

**Comment by L-e-x-o-n** [comment]
Resolved with #401
