### ISSUE TITLE
Increase ping pong timeout delay

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#4]
As spring luamenu is unresponsive while pathing, users drop from the lobby when joining games often

**Comment by Teifion** [comment]
Heartbeat requirement is 45 seconds with a check interval of 30 seconds. How long does it need to be?

**Comment by Beherith** [comment]
Maybe double that, can there be negative side effects of doing so?

**Comment by Teifion** [comment]
Nothing we'd notice at this stage. I'll increase the change in the code tonight and release tomorrow with the username fix.
