### ISSUE TITLE
Disconnect on `s.lobby.add_bot`

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#41]
![image](https://user-images.githubusercontent.com/1434248/176049212-1cab59f5-89c8-4651-923f-f15583612d1a.png)

Tachyon connection getting immediately closed upon receiving this response, I suspect some error server-side.

**Comment by Teifion** [comment]
Almost certainly a server issue, I've not written anything to test Tachyon and bots yet so I'll try to get that sorted for you asap.
