### ISSUE TITLE
[Bug]: Inconsistent rating for Team FFA

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/teiserver#419]
### Describe the Bug

See this discord. https://ptb.discord.com/channels/549281623154229250/1274719624772190249/1274719624772190249
Look at the replay which seems to put armsonar with a weak player even though he appears as a weak player too.

### Reproduce the bug

This will occur with any Team FFA.

### Additional context

When SPADS asks for rating (which will display) we use this code (inside spads_controller.ex)
```
    actual_type =
      case type do
        "Team FFA" -> "Large Team"
        v -> v
      end
```

Yet for balancing we use this:
```
          # Temporary solution until Team FFA ratings are fixed
          rating_type =
            case rating_type do
              "Team FFA" -> "FFA"
              v -> v
            end
```

These are inconsistent.

**Comment by L-e-x-o-n** [comment]
Relevant issue #337

**Comment by L-e-x-o-n** [comment]
Closing in favour of existing #337.
