### ISSUE TITLE
Tachyon connections should be gracefully closed upon error

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#42]
When there's an error with a tachyon connection, Teiserver immediately disconnects the client without providing any message or info as to why. I understand it could be a potential security flaw to send back the full crash info/stack, but I think the server should at least maybe send some error response before forcefully closing the connection, even if it's just something like:

```json
{ "cmd": "s.system.error", "message": "The server has encountered an error, this connection will be terminated" }
```

**Comment by Teifion** [comment]
It's not caused by security but by the way OTP works. The disconnects you are seeing are server errors and they cause the process to die. I will see what I can do about making it send a final message explaining the situation though (I already have stacktrace logs on my end).

**Comment by Teifion** [comment]
I've had a look into it and unfortunately I've not found a way to send a message on process close if there's an error, OTP completely kills the process and it ends there.
