### ISSUE TITLE
`team_color` property of client response should be a string

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#46]
In some cases it's correctly a string, but here it's a number:

![image](https://user-images.githubusercontent.com/1434248/184558901-f630c838-4973-4e5e-80e0-c5af692d79ac.png)

**Comment by Teifion** [comment]
Looks like the default start value is `0` but any time it's updated it typically becomes a string. Tomorrow's release should fix it.

**Comment by Teifion** [comment]
Please let me know if this issue is now resolved :)

**Comment by Jazcash** [comment]
Resolved 👍
