### ISSUE TITLE
`icons` property missing for users in `s.user.user_and_client_list` response

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#47]
![image](https://user-images.githubusercontent.com/1434248/184558976-5d974a81-5602-4b46-983e-57d578401b7e.png)
![image](https://user-images.githubusercontent.com/1434248/184558982-5d6d086b-929c-4fad-b403-a51461db39aa.png)

**Comment by Teifion** [comment]
This has been a bug for some time that I started working on and got distracted, thanks for raising it.
