### ISSUE TITLE
Please implement GETUSERID and GETIP commands for SLDB smurf detection

### ISSUE THREAD

**Issue by Beherith** [beyond-all-reason/teiserver#5]
SLDB smurf detector would benefit from having these commands implemented, at Moderator permission level:

GETUSERID
https://github.com/spring/uberserver/blob/339a57bafd79baf31076452eebf1276a17a4700a/protocol/Protocol.py#L2453

`	def in_GETUSERID(self, client, username):
		user = self.clientFromUsername(username, True)
		if user:
			self.out_SERVERMSG(client, 'The ID for <%s> is %s %s' % (username, user.last_mac_id, user.last_sys_id))
		else:
			self.out_SERVERMSG(client, 'User not found.')`

https://github.com/spring/uberserver/blob/339a57bafd79baf31076452eebf1276a17a4700a/protocol/Protocol.py#L2529

`def in_GETIP(self, client, username):
		'''
		Get the current or last IP address for target user.
		@required.str username: The target user.
		'''
		target = self.clientFromUsername(username)
		if target:
			if target.ip_address in self._root.trusted_proxies:
				ip = "%s via proxy %s" % (target.local_ip, target.ip_address)
			else:
				ip = target.ip_address
			self.out_SERVERMSG(client, '<%s> is currently bound to %s' % (username, ip))
			return

		ip = self.userdb.get_ip(username)
		if ip:
			self.out_SERVERMSG(client, '<%s> was recently bound to %s' % (username, ip))
`

**Comment by Teifion** [comment]
I actually implemented these yesterday but didn't push them. See commit [e6fce19984d13832ba99f29bc4daa2407a62d1c2](https://github.com/beyond-all-reason/teiserver/commit/e6fce19984d13832ba99f29bc4daa2407a62d1c2). I expect it to be pushed live tomorrow morning when I've cleaned up some other stuff I was working on.

**Comment by Beherith** [comment]
Oh, thanks dude :D  you are amazing!
