### ISSUE TITLE
Server seems to think client is still in a battle it shouldn't be in

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#52]
I'm seeing `s.lobby.say` responses for battles I left, although not quite sure of the repro steps. I think possibly joining a different battle still gives updates for the old ones

**Comment by Teifion** [comment]
Just to check, you are leaving the battle by sending a `c.lobby.leave` command?

Is it happening every time or just some of the times?

**Comment by Jazcash** [comment]
Yep, have been sending that command, will try and get some more exact repro steps later

**Comment by Teifion** [comment]
Per an update from Jazcash. Manually leaving works but switching lobby means you are still getting updates from the one you should have left.
