### ISSUE TITLE
Unable to start game, inconsistent team/ID configuration for player or AI bot

### ISSUE THREAD

**Issue by 6AKU66** [beyond-all-reason/teiserver#53]
Pretty annoying thing and probably some even giving up on play because they don't know that removing and adding AI bot often solve this problem.
![Снимок6](https://user-images.githubusercontent.com/89547444/188254116-7e3ee7a9-4e2a-4bdd-9cb4-65407acf545a.PNG)

**Comment by Teifion** [comment]
This is a SPADS item, the server isn't sending this message.

**Comment by 6AKU66** [comment]
@Teifion Is there bug tracker for SPADS things?

**Comment by Teifion** [comment]
Not that I know of, I'd post it in the discord.
