### ISSUE TITLE
Suspected Tachyon crash

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#57]
Tachyon is currently forcibly disconnecting the socket after about 2 minutes:

![image](https://user-images.githubusercontent.com/1434248/191308295-9211aeee-e60b-410b-8a2e-aebd6b22cafc.png)

**Comment by Teifion** [comment]
Fixed by 8b77452250b3a88e506bb1d6eda7cbf157bda7f7
