### ISSUE TITLE
Offline friend info

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#59]
For endpoints such as `s.user.list_friend_users_and_clients`, would it be possible to return information about offline friends here as well as online ones, perhaps distinguished by some `isOffline` flag?

**Comment by Teifion** [comment]
We could do it by just not having a client entry for that user, would that work?

**Comment by Jazcash** [comment]
> We could do it by just not having a client entry for that user, would that work?

Yep, that should be fine

**Comment by Teifion** [comment]
The recent fix for `s.user.list_friend_users_and_clients` should have the required formatting for you. Please let me know if there's anything else to change on it.
