### ISSUE TITLE
`s.user.list_friend_users_and_clients` returns non-friend users

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#60]
![image](https://user-images.githubusercontent.com/1434248/194177615-5df8d9b6-36d5-41e9-aa7b-e3994f45c67b.png)

Don't think the account I'm using (jaztest1) has any friends, but it definitely doesn't have these 50 people

**Comment by Teifion** [comment]
Okay, that's a bug!

**Comment by Teifion** [comment]
I've made a tweak and unit tests suggest it works. I've hotfixed it in, please test and let me know if it fixes the issue.

**Comment by Jazcash** [comment]
Fixed ty
