### ISSUE TITLE
`s.user.list_friend_users_and_clients` users response missing expected data

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#61]
![image](https://user-images.githubusercontent.com/1434248/194178099-60621e33-0f9b-4227-8099-bb7fef5cc6c9.png)

Currently the user data only has `id`, `name` and `clan_id`. Expecting the normal user data response here, which I currently have defined as:

```typescript
{
    id: number;
    springid: number;
    name: string;
    bot: boolean;
    clan_id: number | null;
    country: string;
    icons: Record<string, any>;
}
```

**Comment by Teifion** [comment]
Cheers, another bug.

**Comment by Teifion** [comment]
The hotfix applied earlier should also fix this issue.

**Comment by Teifion** [comment]
I forgot to mention, `spring_id` has been dropped. I'll update the docs soon.
