### ISSUE TITLE
Allow friend endpoints to use `username` or `user_id`

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#64]
Endpoints like `c.user.add_friend`, `c.user.rescind_friend_request` etc all require `user_id`, but as `username` is also a unique field, would it be possible to provide that instead?

**Comment by Teifion** [comment]
Long term I want username to not be unique. It's only unique as long as we support Spring. As such I'd rather not open that door only to later have to close it and break stuff.

**Comment by Jazcash** [comment]
Fair enough
