### ISSUE TITLE
Additional data needed in `s.auth.login` for friend requests and ignored users

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/teiserver#66]
Current:

![image](https://user-images.githubusercontent.com/1434248/195192917-cba54d27-388e-4bf4-bd79-980c36e958db.png)

Needed data:

- `outgoing_friend_requests`: userIds this user has sent friend requests to but haven't been accepted or declined yet
- `incoming_friend_requests`: userIds of users that have sent friend requests to this user but that haven't been accepted or declined yet
- `ignored_users`: userIds this user has set to ignore

A imo scrap `friend_requests` because it's not clear if this is for incoming or outgoing requests

**Comment by Teifion** [comment]
:+1:
