### ISSUE TITLE
The command $minratinglevel uses teams TS even in 1v1 lobbies

### ISSUE THREAD

**Issue by PROrANDY** [beyond-all-reason/teiserver#85]
This has prevented some 1v1 specialists being able to unspec in $minratinglevel games that they should be able to play.

**Comment by L-e-x-o-n** [comment]
Cause of the issue is at line https://github.com/beyond-all-reason/teiserver/blob/7b89900ddb393f6066b7a290bdd5053068f3287f/lib/teiserver/coordinator/consul_server.ex#L830.
Min/max ratings always use Team. Should probably check game type (using Teiserver.Battle.MatchLib.game_type/2 maybe?)
